name: Build and Deploy Documentation

on:
  push:
    branches:
      - documentation
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build the documentation.
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08
      - name: Install, build, and upload documentation
        uses: withastro/action@9a7959a16949e620a22e74f81c10cb7ce3b76924
        with:
          path: ./docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@027b0ddc3de8dbe7e5a699814c4508ca8ecefc5f
        with:
          path: ./docs/dist

  # Deploy the documentation to GitHub Pages.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@7a9bd943aa5e5175aeb8502edcc6c1c02d398e10
