name: Label issues

on:
  issues:
    types:
      - reopened
      - opened

permissions:
  issues: write

jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@1f16022c7518aad314c43abcd029895291be0f52
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["triage"]
            })
