name: Push Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited

permissions:
  contents: read

jobs:
  security-checks:
    uses: ./.github/workflows/run-security-checks.yml
    secrets: inherit